FROM osrm/osrm-backend:latest

# Copy file bản đồ vào đúng path trong container
COPY hanoi-latest.osm.pbf /data/hanoi.osm.pbf

# Chuẩn bị dữ liệu cho thuật toán MLD
RUN osrm-extract -p /opt/car.lua /data/hanoi.osm.pbf && \
    osrm-partition /data/hanoi.osrm && \
    osrm-customize /data/hanoi.osrm

# Mở cổng 5000
EXPOSE 5000

# Chạy OSRM server
CMD ["osrm-routed", "--algorithm", "mld", "/data/hanoi.osrm"]
